runtime: java
env: flex
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "17"
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301  # Permanent redirect
    script: auto
manual_scaling:
  instances: 1
